import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome!</h1>
      
      <div style={{display:'grid', gridTemplateColumns:'auto auto'}}>
        <Link href='/csr'><h2>CSR</h2></Link>
        <Link href='/ssr'><h2>SSR</h2></Link>
        <Link href='/ssg'><h2>SSG</h2></Link>
        <Link href='/isr'><h2>ISR</h2></Link>
      </div>
      <style jsx>{`
        h2:hover{
          cursor: pointer;
          color: darkred
        }
        h1, h2 {
          text-align: center
        }
      `}</style>
    </div>
  )
}
